<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ImPark.Game</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ImPark.Core\ImPark.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
  </ItemGroup>
</Project>
